name: Deploy React App

on:
  push:
    branches: main
    
env:
  CI: false

jobs:
  deploy:

    runs-on: virtualfashion

    steps:
    - uses: actions/checkout@v2
    - run: |
        whoami
        pwd
        ls -la
    - run: |
        git rm --cached admin
        cd frontend
        yarn install
        yarn build
